apiVersion: batch/v1
kind: Job
metadata:
  name: backend-integration-tests
  namespace: wanderlust
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded,HookFailed
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: tests
          image: alisarfraz13/wanderlust-backend-beta:v3
          command: ["npm", "run", "test:integration"]
          env:
            - name: MONGODB_URI
              value: mongodb://mongo-service:27017/wanderlust
            - name: REDIS_HOST
              value: redis-service
